mednote/mednote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('note/', include('note.urls')),
    path('admin/', admin.site.urls),
]

mednote/note/urls.py
from django.urls import path
from . import views

app_name = "note"
urlpatterns = [
    path('',views.index, name = 'index'),
    path('convert/',views.convert,name='convert'),
]

mednote/note/models.py
from django.db import models

# Create your models here.
class NoteText(models.Model):
    raw_text = models.TextField(max_length=3000,default="type in text to convert")
    coverted_text = models.TextField(max_length=3000,default="type in text to convert")
    pub_date = models.DateTimeField()


class AbbreviationList(models.Model):
    user = models.CharField(max_length=200)
    def __str__(self):
        return self.user




class Abbreviation(models.Model):
    abbreviation_list = models.ForeignKey(AbbreviationList, on_delete=models.CASCADE,default=AbbreviationList.objects.filter(user="sanders")[0])
    abbreviation = models.CharField(max_length=200, unique=True)
    full_form = models.CharField(max_length=400)
    def __str__(self):
        return self.abbreviation

mednote/note/views.py
from django.shortcuts import render, HttpResponse
from .models import AbbreviationList,Abbreviation
import string
import re

# Create your views here.

def index(requst):
    abbr_list = AbbreviationList.objects.filter(user='sanders')[0]
    abbrs = Abbreviation.objects.filter( abbreviation_list=abbr_list)
    context = {"abbr_list":abbr_list, "abbrs":abbrs}

    return render(requst,'note/index.html',context)



def convert(request):

    #convert note
    # converted_note = convert_abbreviations_to_full_form(request.POST["rawnote"])
    if request.POST:
        converted_note = convert_abbreviations_to_full_form(request.POST["rawnote"])
    else:

        converted_note = ""

    return render(request,'note/index.html',
                  {"rawnote":"" if not request.POST else request.POST["rawnote"],
                   "converted_note":converted_note}
                  )


def convert_abbreviations_to_full_form(rawnote):
    abbr_list = AbbreviationList.objects.filter(user='sanders')[0]
    abbrs = Abbreviation.objects.filter( abbreviation_list=abbr_list)
    abbrs_dict = {}
    punctuation = set(string.punctuation)
    for abbr in abbrs:
        abbrs_dict[abbr.abbreviation] = abbr.full_form

    word_list = re.findall(r"[\w/']+|[.:,!?;]", rawnote)

    for idx,word in enumerate(word_list):
        if word.lower() in abbrs_dict:
            word_list[idx] = abbrs_dict[word.lower()]


    # return " ".join(word_list)
    return " ".join(word_list)

mednote/note/templates/note/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Abbreviation converter - Sanders Lin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" type="text/css" href={% static "bootstrap/css/bootstrap.min.css"%} />
    <link rel="stylesheet" type="text/css" href={% static "font-awesome/css/font-awesome.min.css"%} />

    <script type="text/javascript" src={% static "js/jquery-1.10.2.min.js"%}></script>
    <script type="text/javascript" src={% static "bootstrap/js/bootstrap.min.js"%}></script>
</head>
<body>

<div class="container">

<div class="page-header">
    <h1>Medical Note Abbreviation Converter<br><small>A croudsourced abreviation converting app </small></h1>
</div>

<!-- Contact Form - START -->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" action="{% url 'note:convert' %}" method="post" id="rawNoteForm">


                	{% csrf_token %}
                    <fieldset>
                        <legend class="text-center header">Converter</legend>

                   		<div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-pencil-square-o bigicon"></i></span>
                            <div class="col-md-8">
                                <textarea class="form-control" id="rawnote" name="rawnote" form="rawNoteForm" placeholder="Enter your note here and press convert to see the results at the bottom textbox" rows="7">{{rawnote}}</textarea>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Convert</button>
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-pencil-square-o bigicon"></i></span>
                            <div class="col-md-8">
                                <textarea class="form-control" id="message" name="convertedNote" placeholder="The converted note will appear here." rows="7">{{converted_note}}</textarea>
                            </div>
                        </div>


                        



                         <div class="form-group">
                            <div class="col-md-12 text-center">
                                

                                <button class="btn btn-primary btn-lg"  onclick="location.href='/admin/note/abbreviation/'" type="button">
Edit abbreviation List</button>

                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
    .header {
        color: #36A0FF;
        font-size: 27px;
        padding: 10px;
    }

    .bigicon {
        font-size: 35px;
        color: #36A0FF;
    }
</style>

<!-- Contact Form - END -->

</div>

</body>
</html>

mednote/note/templates/note/index_og.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>note converter</title>
</head>
<body>
	<h1>The awesome note converter v.1.1 {{foo}}</h1>
	


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


	<!-- form -->


<form action="{% url 'note:convert' %}" method="post" id="rawNoteForm">
{% csrf_token %}

<textarea rows="4" cols="50" name="rawnote" form="rawNoteForm">
{{rawnote}}</textarea>

<br>
<input type="submit" value="Convert!">
</form>

<!-- form ends -->

<p>type in text to convert.</p>

<h2>Converted Note</h2>
<textarea rows="4" cols="50" name="convertedNote">
{{converted_note}}</textarea>

<br>
<button onclick="location.href='/admin/note/abbreviation/'" type="button">
Edit abbreviation List</button>


<img src="{% static 'note/dingo.jpg' %}" alt="My image">

</body>
</html>